name: Common CI Workflow

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run CI Steps
        run: echo "Running CI for ${{ inputs.service_name }}"

  trigger-smoke-tests:
    needs: ci_pipeline

    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/VamsiNGV/cypress/dispatches \
          -d '{"event_type":"trigger-smoke-tests"}'
    
    # secrets: inherit
    # uses: VamsiNGV/cypress/.github/workflows/smoke-test.yml@main
    
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Trigger Smoke Tests
        
        # with:
        #   workflow: "smoke-test.yml"
        #   repo: "VamsiNGV/cypress"
        #   token: ${{ secrets.GH_PAT }}
